[package]
name = "stack"
version = "0.1.0"
authors = ["Gabie <jacadel1998@hotmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3.4"
bounded-vec-deque = "*"
regex = "1"
lazy_static = "1.4.0"
strum = "0.19"
strum_macros = "0.19"
num_enum = "*"